import "./globals.css";
import { Noto_Sans } from "next/font/google";

const font = Noto_Sans({ subsets: ["latin"], weight: "800" });

export const metadata = {
    title: "IMDb clone",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={font.className}>{children}</body>
        </html>
    );
}
