import Header from "@/components/Header";
import "./globals.css";
import { Noto_Sans } from "next/font/google";

export const metadata = {
    title: "IMDb clone",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Header />

                {children}
            </body>
        </html>
    );
}
